// Generated by CoffeeScript 1.7.1
define("binnng/url.js", function(require, exports, module) {
  var DOC, URL, WIN, decode, entry, getDataFromParams, _URL;
  WIN = window;
  DOC = document;
  decode = WIN["decodeURIComponent"];
  getDataFromParams = function(params) {
    var item, querys, ret, setDataFromParam, _i, _len;
    ret = {};
    querys = params.split("&");
    setDataFromParam = function(item) {
      var name, value;
      item = item.split("=");
      name = item[0];
      value = item[1] || "";
      return ret[decode(name)] = decode(value);
    };
    for (_i = 0, _len = querys.length; _i < _len; _i++) {
      item = querys[_i];
      setDataFromParam(item);
    }
    return ret;
  };
  _URL = (function() {
    var WIN_URL, isSurportURL;

    WIN_URL = WIN["URL"];

    isSurportURL = typeof WIN_URL === "function";

    function _URL(url) {
      var hash, search, _ref, _ref1;
      this.url = url;
      this.search = this.hash = null;
      search = (_ref = url.split("?")) != null ? _ref[1] : void 0;
      if (search) {
        this.search = "#" + search;
      }
      hash = (_ref1 = url.split("#")) != null ? _ref1[1] : void 0;
      if (hash) {
        this.hash = "#" + hash;
      }
    }

    return _URL;

  })();
  URL = {
    parse: function(url) {
      return new _URL(url);
    },
    search: function(url) {
      var ret, search;
      if (url == null) {
        url = "";
      }
      url = URL.parse(url);
      search = url.search;
      ret = search ? getDataFromParams(search.substr(1)) : null;
      return ret;
    },
    hash: function(url) {
      var hash, ret;
      if (url == null) {
        url = "";
      }
      url = URL.parse(url);
      hash = url.hash;
      ret = hash ? getDataFromParams(hash.substr(1)) : null;
      return ret;
    },
    getDataFromParams: getDataFromParams
  };
  entry = URL;
  return module.exports = entry;
});
